### ISSUE TITLE
Add additional modules

### ISSUE THREAD

**Issue by justafish** [jsdrupal/drupal-admin-ui-demo#2]
- [x] Include and enable the [Admin UI support module](https://github.com/jsdrupal/drupal-admin-ui/tree/master/admin_ui_support). I guess this should track with releases from https://github.com/jsdrupal/drupal-admin-ui-dist ?
- [x] Add and enable JSON API
- [x] Use Drush to enable the required modules
- [x] Setup CORS by default

**Comment by dawehner** [comment]
I added a point about providing a small install profile which enables the modules as needed

**Comment by justafish** [comment]
@dawehner instead of an installation profile, would it be possible to include drush as a dependency and run commands to download and enable jsonapi in `post-install-cmd` ?

**Comment by justafish** [comment]
hmm apparently not because the `@php docroot/core/scripts/dev-site.php start` doesn't run in the background :)

**Comment by dawehner** [comment]
We could still do that when we execute drush before ``` @php docroot/core/scripts/dev-site.php start```

**Comment by justafish** [comment]
@dawehner I tried that, but it unfortunately didn't work (because the web server isn't running so it can't enable the module I assume :) )

**Comment by dawehner** [comment]
@justafish Mh, so I'm highly confused. Why would drush require a webserver instance of Drupal? There is one problem I stumbled upon: https://www.drupal.org/project/drupal/issues/2911319#comment-12536571
