### ISSUE TITLE
Transition to Drupal 8.7

### ISSUE THREAD

**Issue by martinfrances107** [jsdrupal/drupal-admin-ui-demo#22]
**If** our policy is to work against the current development branch of Drupal, then we should move to D7.x 

#21

**Comment by dawehner** [comment]
Do we need to update ```        "webflo/drupal-core-require-dev": "~8.6",
``` too?

Note: We should also update the look file

**Comment by martinfrances107** [comment]
I have made a PR to update composer.lock

**Comment by martinfrances107** [comment]
I have made a PR to update composer.lock

**Comment by lauriii** [comment]
This has been fixed by #21
