### ISSUE TITLE
Installer doesn't work

### ISSUE THREAD

**Issue by justafish** [jsdrupal/drupal-admin-ui-demo#5]
Running the command from the README gives:
```
[InvalidArgumentException]                                                
  Could not find package jsdrupal/drupal-admin-ui-demo with stability dev.
```

**Comment by dawehner** [comment]
I assume the problem is that it still points to the old repository name.

@alexpott needs to push the new package up, or well, ideally invite us to the namespace so we can create new ones, too.

**Comment by alexpott** [comment]
https://packagist.org/packages/jsdrupal/drupal-admin-ui-demo exists.

I looked for how to add people to the namespace - can't see how yet.

**Comment by dawehner** [comment]
We might need to create a shared account somehow.

Note: Right now the next block is caused by https://github.com/jsdrupal/drupal-admin-ui/pull/49

**Comment by dawehner** [comment]
https://github.com/jsdrupal/drupal-admin-ui-demo/pull/7 seems to work now properly.

**Comment by alexpott** [comment]
@justafish and @dawehner are now maintainers on https://packagist.org/packages/jsdrupal/drupal-admin-ui-demo - should other peeps be?

**Comment by alexpott** [comment]
I've added everyone in the jsdrupal project that has a packagist account. The bus factor is no longer a factor!

**Comment by justafish** [comment]
Works great now, thank you! 👍
